[package]
name = "bdf-reader"
version = "0.0.0"
publish = false
edition = "2021"

license = "EPL-2.0"
description = "BDF font format reader"

[dependencies]
bit-vec = "0.6"
paste = "1.0"
thiserror = "1.0"
